export const CAL_TEST_IDS = {
  newEventType: "new-event-type",
  eventTypeQuickChat: "event-type-quick-chat",
  eventTypeOptions: (id: string): string => `event-type-options-${id}`,
  dialogConfirmation: "dialog-confirmation",
  bookerContainer: "booker-container",
  timeSlot: "time",
  timezoneSelectOption: (iana: string): string => `select-option-${iana}`,
  confirmBook: "confirm-book-button",
  bookingFail: "booking-fail",
  bookerBack: "back",
  successPage: "success-page",
  newSchedule: "new-schedule",
  schedules: "schedules",
  availabilityTitle: "availability-title",
  updateEventType: "update-eventtype",
  scheduleMore: "schedule-more",
  deleteSchedule: "delete-schedule",
} as const;
